language: r
os: linux
cache: packages
dist: trusty

r_binary_packages:
  - mapproj
  - ggplot2
  - maps
  - covr

jobs:
  include:
    # - os: linux
    #   r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    # - os: linux
    #   r: devel
    #   env: _R_CHECK_LENGTH_1_LOGIC2_=verbose

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran --run-dontrun"

notifications:
  email:
    on_success: never
    on_failure: never
